### PR TITLE
Dockerized wings daemon

### PR DESCRIPTION
**Pull request by HoverEpic**
The Wings daemon can now be setup as a docker container.
Hacked fiew things to get it working.

### CODE REVIEW

**Comment by DaneEveritt** [comment]
Is there a reason this needs to support Raspbian?

**Comment by HoverEpic** [comment]
I can code something quick to show you why this hack if needed.
`os.dist` returns "Raspbian" on Alpine 3.7 ><

Edit : 
image

**Comment by hendrikbl** [comment]
Any news on this? I'd love to use Pterodactyl in a container to clean up my server :)

**Comment by birkhofflee** [comment]
@hendrikbl https://github.com/BirkhoffLee/pterodactyl-daemon-Dockerfile

**Comment by parkervcp** [comment]
I have one of these already. I maintain it and everything.

https://github.com/parkervcp/pterodactyl-daemon-Dockerfile

Birkhoffs is literally a fork of a fork of mine.

**Comment by schrej** [comment]
It's actually forked from https://github.com/sachk/pterodactyl-daemon-dockerfile who added multistage builds, which is kinda nice.

**Comment by parkervcp** [comment]
I don't see why a multistage build would be needed though.

**Pull request closed without merging**
