### PR TITLE
Fix XML config parsing

### PR DESCRIPTION
**Pull request by nsgomez**
Fs.read requires a file descriptor and fails with a filename, use Fs.readFile instead as the file and ini parsers do.

### CODE REVIEW

**Comment by schrej** [comment]
@parkervcp can you test if this fixes the issues you were having?

**Comment by parkervcp** [comment]
@schrej I can test this out later.

Thanks @nsgomez we were looking into this int he background because it was breaking some stuff for a game.

**Comment by parkervcp** [comment]
I have found I have no idea what the json layout for xml should be to edit things in xml.

Currently I have this
```
{
    "serverconfig.xml": {
        "parser": "xml",
        "find": {
            "ServerPort": "{{server.build.default.port}}"
        }
    }
}
```

I am trying to edit this
```
<ServerSettings>
    <property name="ServerPort" value="26900"/>
</ServerSettings>
```

this just adds a `<root>` section to my xml file.

**Comment by nsgomez** [comment]
@parkervcp Not sure about attributes but this is the config I'm using to control an Icecast server for now:
```json
{
    "config.xml": {
        "parser": "xml",
        "find": {
            "icecast.hostname": "{{server.build.env.ICECAST_HOSTNAME}}",
            "icecast.listen-socket[0].port": "{{server.build.default.port}}",
            "icecast.authentication[0].source-password": "{{server.build.env.SOURCE_PASS}}",
            "icecast.authentication[0].relay-password": "{{server.build.env.RELAY_PASSWORD}}",
            "icecast.authentication[0].admin-user": "{{server.build.env.ADMIN_USERNAME}}",
            "icecast.authentication[0].admin-password": "{{server.build.env.ADMIN_PASSWORD}}",
        }
    }
}
```

Which produces
```xml
<icecast>
    <hostname>{{server.build.env.ICECAST_HOSTNAME}}</hostname>
    <listen-socket>
        <port>{{server.build.default.port}}</port>
    </listen-socket>
    <authentication>
        <source-password>{{server.build.env.SOURCE_PASS}}</source-password>
        <relay-password>{{server.build.env.RELAY_PASSWORD}}</relay-password>
        <admin-user>{{server.build.env.ADMIN_PASSWORD}}</admin-password>
        <admin-password>{{server.build.env.ADMIN_PASSWORD}}</admin-password>
    </authentication>
</icecast>
```

**Pull request merged**
