### PR TITLE
Add backup of ptero.co if hastebin fails. 

### PR DESCRIPTION
**Pull request by notAreYouScared**
Hastebin has been unstable over the last few weeks

### CODE REVIEW

**Comment by notAreYouScared** [comment]
Could this get merged? Hastebin is still dying.

**Comment by schrej** [comment]
@DaneEveritt ptero.co is owned by AreYouScared#7657. Do we want to use it or host our own hastebin or send it to https://bin.ptdl.co/ instead?
I'd be fine with using AreYouScared's hastebin, as long as he keeps it running...

**Comment by schrej** [comment]
Sending to bin.ptdl.co is actually quite simple:
```js
var net = require('net');

function uploadToPtdlBin(text) {
  return new Promise((resolve, reject) => {
    var client = new net.Socket();
    client.connect(99, 'bin.ptdl.co', () => {
      client.write(text);
    });

    client.on('data', url => {
      resolve(String(url));
      client.destroy();
    });
    client.on('error', reject);
  });
}
```

**Comment by notAreYouScared** [comment]
It's mostly still only a backup, hastebin dies then its basicaly almost impossible to help people whe. We ask for logs. Sure you could use bin.ptdl.co but I've asked Dane a while back about it and he said he didn't have time to set it up so I was taken the burdon off him, so I made my own and bought the domain. Yes I'm AreYouScared.

**Comment by DaneEveritt** [comment]
Can I make this more work and just make it an option picker (1,2,3) to pick which service to upload to? Then we can have all 3 and let the user pick whatever they're wanting. You're welcome to default it to your service as well, it doesn't bother me.

**Comment by notAreYouScared** [comment]
I feel if we gave them a choice, those not so smart people would be asking which one to pick. I'm sure nobody wants that extra stop of confusion

**Review by DaneEveritt — APPROVED** [review]

**Comment by DaneEveritt** [comment]
Please fix the errors: https://travis-ci.org/pterodactyl/daemon/jobs/479132039

**Comment by notAreYouScared** [comment]
I'll look into it when I get off work

**Comment by notAreYouScared** [comment]
When in doubt, ignore the line....

**Comment by schrej** [comment]
I would prefer to just use one service. I'm also fine with a full switch to ptero.co instead of hastebin if it's down frequently, instead of just using it as a backup.

**Comment by notAreYouScared** [comment]
I personally don't care. I feel I'd like to have a backup just in case, hastebin has slowly getting better but still seems to have some eh moments

**Pull request merged**
