### PR TITLE
Fix systemCompress to support multiple files

### PR DESCRIPTION
**Pull request by TrixterTheTux**

### CODE REVIEW

**Review by DaneEveritt — COMMENTED** [review]
Can’t you just remove the .join() on files in the original statement?

**Comment by TrixterTheTux** [comment]
After testing that, it wouldn't work. It doesn't error but the archive resulted by it is just empty. ``require("child_process").spawn("tar",["czf","test.tar",["a.txt","b.txt"]]).on("error",console.log);``

**Comment by DaneEveritt** [comment]
Oh, I see because its an array in an array.

**Comment by DaneEveritt** [comment]
@TrixterTheTux please fix the code so it passes the Travis-CI tests. :)

**Comment by DaneEveritt** [comment]
implemented in 7881e3b

**Pull request closed without merging**
